### ISSUE TITLE
Questions/remarks regarding the migration/deprecation guide

### ISSUE THREAD

**Issue by bertdeblock** [ember-engines/ember-engines.com#112]
I feel it's not really clear what's actually being deprecated. If you analyse the before and after examples you kind of get the gist of it, but I feel the copy itself could be clearer. Maybe something like:

> Defining a dependency on the host's router service as `router` has been deprecated. Please specify an alternative name. E.g. `{ 'host-router': 'router' }`.

The guide also mentions: `we don't want to automatically create either of these services`.
Which other service is the guide talking about?

The after example also contains a syntax error: `{ 'host-router'}: 'router',` and I think we should also update the engine name from `superBlog` to `'super-blog'` as camelized engine names are also deprecated (which we should probably also add to the guides?).

**Comment by villander** [comment]
> Which other service is the guide talking about?

Router Service has been pointed in the title of the section. Do you have any better text to replace that? 

![image](https://user-images.githubusercontent.com/10222774/114272247-cd8f0a80-99eb-11eb-9284-f05e4ff35e27.png)


> The after example also contains a syntax error: { 'host-router'}: 'router'

Good point, but I think it's not a serious issue, could be fixed later - I'd like to consider it a typo - feel free to submit a PR for that.

> I think we should also update the engine name from superBlog to 'super-blog'

I disagree here, it has been changed for all scenarios which implies change all examples on docs with this new deprecation - what makes sense here is another issue for that to modernize our docs.

**Comment by bertdeblock** [comment]
> Router Service has been pointed in the title of the section.

The current title is misleading I feel. Now, it sounds like defining a dependency on the host router is deprecated entirely, which isn't the case I think? You are still allowed to define the dependency, you just need to use a different name like `host-router`. So I still feel the deprecation guide should make it more clear that it's about the name. The example I included in my initial comment seems clearer to me.

Also, since the word `services` (plural) is used in the description, it seems like the guide is talking about _multiple_ services. I don't know, reading it confused me as I assumed the deprecation is only about _one_ service: the router service.

Regarding the engine name in the after example. Maybe it's just me, but I find it strange that a deprecation guide uses something that is deprecated as well. Sure, the actual deprecation about the engine names isn't released yet, but that's the case as well for this deprecation.

**Comment by villander** [comment]
> The current title is misleading I feel. Now, it sounds like defining a dependency on the host router is deprecated entirely, 

It's not true, it sounds what it says - **Host router service** it doesn't say `service:router` or `router:main` directly. We can improve it for sure, but I don't think it's causing confusion to understanding.

**Comment by bertdeblock** [comment]
Maybe to you, the author of the guide, the title was clear enough. To me, the reader, I can only stress that it wasn't. Thanks for updating.
