### ISSUE TITLE
Add `ember g in-repo-engine` to guides section.

### ISSUE THREAD

**Issue by rwjblue** [ember-engines/ember-engines.com#15]
Should be mentioned on http://ember-engines.com/guide/creating-an-engine.

**Comment by drewcovi** [comment]
so im just digging into this fantastic addon right now. since this issue is growing stale, i can easily sling markdown/html and help with this undertaking.

or is there a larger effort underway which is why this issue has stalled for the year?

**Comment by trentmwillis** [comment]
@drewcovi I just don't think anyone ever got around to it, so a contribution is definitely still welcome!

Would also be worth mentioning the [standalone engine blueprint](https://github.com/ember-engines/engine-blueprint).

**Comment by villander** [comment]
@rwjblue this issue can be closed now 🎉
