### ISSUE TITLE
Strange heading

### ISSUE THREAD

**Issue by samselikoff** [ember-engines/ember-engines.com#19]
Looks like something that's autogenerating headings is hashing a title in [this section](http://ember-engines.com/guide/creating-an-engine)?

![image](https://cloud.githubusercontent.com/assets/2922250/22352392/d5694cfa-e3d0-11e6-8c5f-f2f88fd4c751.png)

**Comment by trentmwillis** [comment]
Looks like broccoli-asset-rev is running amuck. Should definitely fix.

**Comment by perlun** [comment]
This is still an issue, it looks truly bizarre.
