### ISSUE TITLE
`resetNamespace` undocumented for Ember > 2.1.0

### ISSUE THREAD

**Issue by DavidPhilip** [ember-engines/ember-engines.com#31]
I saw that the `resetNamespace` option is mentioned in the guides of ember-engines but not documented anymore for newer versions of Ember (https://github.com/emberjs/guides/commit/fff43efa03fafef6b23d1c7f9d231b08a00336a2).

Could you give us some insights why this is so?

**Comment by villander** [comment]
@DavidPhilip this is a issue to `Ember guides` 

`resetNamespace` has been in the older guides, and still exists in Ember.js codebase.
I suggest you close this issue and open it in the correct repository

https://guides.emberjs.com/v2.0.0/routing/defining-your-routes/#toc_resetting-nested-route-namespace

https://github.com/emberjs/ember.js/search?p=1&q=resetNameSpace&type=&utf8=%E2%9C%93

**Comment by villander** [comment]
@rwjblue we can close this issue?
