### ISSUE TITLE
migrate markdown resolver usage to other docs tool

### ISSUE THREAD

**Issue by ghost** [ember-engines/ember-engines.com#50]
<img width="1100" alt="screen shot 2019-01-23 at 15 49 07" src="https://user-images.githubusercontent.com/472721/51636157-8c070780-1f26-11e9-8d1f-d5e234e88744.png">

Tools we should consider using for generating the docs in this project:
* [ember-cli-addon-docs](https://github.com/ember-learn/ember-cli-addon-docs)
* [broccoli-static-site-json](https://github.com/empress/broccoli-static-site-json)

Per @villander , this isn't a top priority, but would be nice to have.
@buschtoens graciously offered to help convert to `ember-cli-addon-docs` 😄

**Comment by abhilashlr** [comment]
What do we plan to use YUIDoc or ESDoc for generating the addon docs?

**Comment by villander** [comment]
Thanks a lot for the hard work @gabrielcsapo
