### ISSUE TITLE
Use ember-cli-addon-docs for built site

### ISSUE THREAD

**Issue by gabrielcsapo** [ember-engines/ember-engines.com#78]
The current site does not allow us to search for information and is cumbersome. When you click into a section, it does not maintain a left rail of all the other options. What are the thoughts on using the default https://github.com/ember-learn/ember-cli-addon-docs to get a better user experience with the docs?

**Comment by gabrielcsapo** [comment]
Looks like this was brought up in https://github.com/ember-engines/ember-engines.com/issues/50

**Comment by gabrielcsapo** [comment]
Any reservations of having me take a shot at doing this tonight? @efx @buschtoens @villander

**Comment by ghost** [comment]
@gabrielcsapo howdy! I don't have any reservations but also have not worked with ember documentation tools in addons. The points you raise are warrant enough for me. I'm always in favor of making documentation and the experience learning with it better. I'd say give it a shot if you are interested!

**Comment by stefanpenner** [comment]
@gabrielcsapo 👍

**Comment by stefanpenner** [comment]
cc @dgeb & @villander

**Comment by villander** [comment]
Awesome @gabrielcsapo. I'm closing it in favor or #50 

Thanks for helping us achieve #55 to deliver a great UX and DX for the ember community.
