### ISSUE TITLE
Duplicated example in guide at "Linking Within An Engine"

### ISSUE THREAD

**Issue by benoror** [ember-engines/ember-engines.com#8]
In [Linking Within An Engine](https://github.com/ember-engines/ember-engines.com/blob/eaa1a35ac3f9fce84c7264a95f944ad7beb5dc8b/markdown/guide/linking-and-external-links.md#linking-within-an-engine) the following example is duplicated:

> Previously we mentioned that each Engine has it's own `application` route, that route corresponds to the mount point when within the Engine. So, if you wanted to go to `super-blog` (or the root of the Engine) from within the Engine itself, you would do something like:
> ```hbs
> {{#link-to "application"}}Blog Home{{/link-to}}
> ```
> Or, maybe even:
> ```hbs
> {{#link-to "application"}}Blog Home{{/link-to}}

**Comment by trentmwillis** [comment]
Corrected by #12.
