### ISSUE TITLE
Fix deploy to heroku

### ISSUE THREAD

**Issue by gabrielcsapo** [ember-engines/ember-engines.com#83]
We currently can’t debug why the docs won’t deploy to heroku.

@dgeb @trentmwillis would you be able to assist?

**Comment by dgeb** [comment]
@gabrielcsapo has this been resolved via #84?

**Comment by villander** [comment]
No @dgeb we're pairing on it. We have many issues to solve =/

**Comment by gabrielcsapo** [comment]
Closing this and opening up a new issue to move cdn over to look at github pages.

**Comment by gabrielcsapo** [comment]
opened this instead https://github.com/ember-engines/ember-engines.com/issues/86
