### ISSUE TITLE
Accidentally fingerprinting of documentation text

### ISSUE THREAD

**Issue by ef4** [ember-engines/ember-engines.com#89]
On this page: 

https://ember-engines.com/docs/lazy-loading

The text reads:

> Lazy engines are built in the same way as eager engines, but their assets are not combined back into the host application's vendor-b8fae49b3b61342eec0bbbd72949609f.js file. This means that they are run through a separate and unique build process from what a default addon will go through, though it reaches out to the upstream implementation in Ember CLI where possible.

Most likely, broccoli-asset-rev saw the string `vendor.js` and tried to helpfully replace it with a fingerprinted version for you.

There's not much to be done upstream in broccoli-asset-rev, it uses a fundamentally unsound strategy. You can probably play tricks, like I think you can set `outputPaths.vendor.js` on your EmberApp to a name other than `vendor.js` so your own vendor file will have a different name that doesn't match the docs.

**Comment by gabrielcsapo** [comment]
Thank you @ef4 will look into a fix for this!
