### ISSUE TITLE
Re-exporting an in-repo addon?

### ISSUE THREAD

**Issue by leizhao4** [ember-engines/ember-engines.com#9]
In _Sharing Components and More_:

> The EngineAddon base class hooks into Ember-CLI's build hooks to automatically re-export addon code into your Engine. 

I understand that it works with standalone addons. But what about in-repo addons? What should I do in my `package.json` if I want EngineAddon to re-export it?

Also, if my component comes with a template, is it going to work? Can templates be imported and exported?

 Thanks!

**Comment by trentmwillis** [comment]
In-repo-addons can be re-exported! You simply have to make sure the in-repo-addon is listed as a dependency via the `paths` property:

```json
{
  "ember-addon": {
    "paths": [
      "./lib/my-in-repo-addon"
    ]
  }
}
```

If your component has a template, you should explicitly link them by defining a `layout` property and then re-exporting the entire component (this is the default when generating a component within an addon).

**Comment by leizhao4** [comment]
Yay! It works now. Thanks for helping!

**Comment by chendraayan** [comment]
I am facing the same issue. 
> You simply have to make sure the in-repo-addon is listed as a dependency via the `paths` property

Should I list the in-repo-addon in my app's package.json or my in-repo-engine's package.json?
@leizhao4  @trentmwillis

**Comment by san018** [comment]
I'm facing the same issue.  After the path being specified and the layout being imported, the in-repo-addon is not accessible in the app or the engine.  @leizhao4 @trentmwillis
