### ISSUE TITLE
Markdown is not woking as expected 

### ISSUE THREAD

**Issue by villander** [ember-engines/ember-engines.com#95]
Hi guys
The markdown is working fine on GitHub repo - https://github.com/ember-engines/ember-engines.com/blob/master/tests/dummy/app/templates/docs/bundling.md

but it doesn't work on site or local - https://ember-engines.com/docs/bundling

any idea why it's happening?

cc: @gabrielcsapo @locks

**Comment by gabrielcsapo** [comment]
The issue was with the styles not the actual html itself. Please see #97.
